name: CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: update submodule
              run: git submodule update --init --depth=1

            - name: Setup python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.7'

            - name: Test pypi install in clean environment
              run: |
                  pip install tinyfk
                  python -c "import tinyfk"
                  pip uninstall tinyfk -y      

            - name: Install apt packages
              run: |
                  sudo apt-get install libeigen3-dev libtinyxml-dev

            - name: Build c++ via cmake
              run: |
                  export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/lib/x86_64-linux-gnu/pkgconfig"
                  mkdir build
                  cd build
                  cmake .. 
                  make

            - name: Test c++
              run: |
                  cd build
                  ./test_kinematics

            - name: pip install tinyfk from source
              run: |
                  pip install numpy pytest
                  pip install . 

            - name: Test python wrapper
              run: |
                  cd python
                  pytest
